# 原书前言 · 本书结构 · 学习日程表 {.unnumbered}

> 出自《英语单词超强记忆法》（〔韩〕金炯卓）　原书扫描页 p1–p15

<!-- p.? -->

快速记忆 33300 个单词
根据单词来源，快速理解单词

**学語者** 知识改变命运，语言畅通世界！

可点读

## 英语单词超强记忆法

## 词汇专家手把手教你玩转英语单词

〔韩〕金炯卓 著
邢心秀 孟丽 译

<!-- 插图：滑板上的卡通瓢虫与点读笔小精灵 -->

上海社会科学院出版社
SHANGHAI ACADEMY OF SOCIAL SCIENCES PRESS

扫一扫，马上开启英语学习之旅！

<!-- p.? -->

学语者 知识改变命运，语言畅通世界！

可点读

## 英语单词超强记忆法

## 词汇专家手把手 教你玩转 英语单词

<!-- 插图：惊讶的卡通男孩与小狗 -->

著 金炯卓（韩）  
译 邢心秀 孟丽  

上海社会科学院出版社  
SHANGHAI ACADEMY OF SOCIAL SCIENCES PRESS

<!-- p.? -->

영단어 무작정 따라하기
ISBN 978-7-5520-1545-4
Copyright © 2011 Kim Hyung Tak
초판 1쇄 인쇄 · 2011년 6월 10일 / 초판 1쇄 발행 · 2011년 6월 20일
上海市版权局著作权合同登记号：图字 09-2016-600

The Cakewall series - Vocabulary
Copyright © 2011 Kim Hyung Tak
Originally published by Gilbut EZtok
Simplified Chinese translation copyright © 2016 Jing Zhen Wen Culture Co., Ltd
This Edition is arranged by Pauline Kim Agency, Seoul, Korea.
No part of this publication may be reproduced, stored in a retrieval system or transmitted in any form or by any means, electronic, mechanical, photocopying, recording, or otherwise without a prior written permission of the Proprietor or Copyright holder.

**图书在版编目（CIP）数据**

英语单词超强记忆法：词汇专家手把手教你玩转英语单词 / （韩）金炯卓著. — 上海: 上海社会科学院出版社, 2016

ISBN 978-7-5520-1545-4

I. ①英… II. ①金… III. ①英语—词汇—记忆术 IV. ①H313

中国版本图书馆CIP数据核字 (2016) 第209076号

---

**英语单词超强记忆法——词汇专家手把手教你玩转英语单词**

主　　编：金炯卓（韩）
责任编辑：庄晓明
封面设计：郁心蓝
出版发行：上海社会科学院出版社
　　　　　上海顺昌路622号　邮编200025
　　　　　电话总机021-63315900　销售热线021-53063735
　　　　　http://www.sassp.org.cn　E-mail:sassp@sass.org.cn
印　　刷：大厂回族自治县正兴印务有限公司
开　　本：787毫米×1092 毫米 1/16 开
印　　张：34.75
字　　数：560千字
版　　次：2017年5月第1版　　2017年5月第1次印刷

---

ISBN 978-7-5520-1545-4/H. 036　　　　　　　　　　　　　　　　定价：58.00元

版权所有　侵权必究

<!-- p.? -->

## 英语单词，不必死记硬背！
## 单词不用死记硬背照样也可以记住的3大秘法！

<!-- 插图：人物根据单词的生成原理培育单词树 -->

### 1. 按单词的“造词原理”去记！

<!-- 插图：讲故事变出单词书 -->

### 2. 通过“故事”熟记单词！

<!-- 插图：生长在书本上的“单词树” -->

### 3. 通过“单词树”串记单词！

理解单词造词规律故事，不用死记硬背单词也可以自然而然地记住单词。熟悉词根，即便出现了不认识的单词，也可以类推出其词义。学会猜词，即使身边没有词典，照样可以顺利阅读英文！

<!-- p.3 -->

## 序言

**您有信心把33000个单词全都背下来吗？不要死记硬背，请尝试着通过理解来记英语单词吧！**

#### 33000个单词，仅靠死记硬背能记下来吗？

如果问英语学习者从哪个部分开始学习，那么不论英语学习高手，还是菜鸟级初学者，他们都会异口同声地表示从“英语单词”开始。所以，着手学习英语的时候，首先要做的就是买本英语单词书。然后，以义无反顾的决心打开书。可是，你会发现书里的单词只是像词典一样列出了词义而已，至于怎样记忆单词，为什么这个单词会是这个意思，在书中找不到答案。用这种跟词典差不多只是列出词义的词汇书，能很好地把33000个单词都背下来吗？

#### 英语单词学习法，从现在开始改变！

反复记忆却仍记不住英语单词，很多人会垂头丧气地说：“我的记忆力太差。”抱有这种想法的人请注意：其实您的记忆力很好！只是所使用的记忆法不太科学而已。让我们丢掉这种反复抄写单词和词义来背诵的原始记忆法！让我们来听听每个单词背后的故事吧，理解了单词的形成背景故事，您无需死记硬背也能轻松地记住单词。

#### 不死记硬背，而从理解单词开始记忆！

《英语单词超强记忆法》由理解英语单词的“三大秘法”所构成，助您全方位立体记忆英语词汇。

#### 就算出现了新单词，照样可以不查词典继续阅读！

《英语单词超强记忆法》精选了各种会话书、考试真题以及英文报刊中出现的高频词汇。本书生动有趣，可以让您像读小说一样津津有味。在合上本书最后一页的瞬间，完全消除背英语单词的抵触感，摇身变成可以轻松地阅读英文报刊的高手。

现在各位的手中已有这本书学习英语的秘笈，接下来就请将它转化成您自己的知识吧！

> **特别鸣谢**  
> 真心感谢在这漫长的三年里，与我一起奋战的耐心的编辑们。同时，也向我的家人表示深深的歉意。因为忙于本书的编写，我不能常伴左右，谨以此书献给我亲爱的家人，谢谢你们的支持与理解。

金炯卓

<!-- p.4 -->

## 英语单词的3大秘法

### 1. 熟知单词的“造词原理”！

单词的造词形成方式丰富多样，有些单词源自于神话、动物或植物名称，有些单词是在词根的前面或后面加上前后缀派生而成。因此，了解单词的造词原理，按其造词原理和规律来记忆的话，会取得良好的记忆效果。

与其他英语词汇学习书不同，本书列举了多种单词造词法，以便读者能够从多角度全方位地记忆单词（如，源自于神话故事的单词，通过词根组合所构成的合成词或词根与词缀组合所形成的派生词，通过音韵变化而形成的词、通过语义扩张所形成的多义词、等等），通过了解这些单词的造词原理来有效地记忆单词。

### 2. 通过“故事”来熟记单词！

如果您把“买椟还珠”这个成语的意思告诉从未听过这个成语的小孩或外国人并让他们必须背下来。那么，过了一段时间后，他们是否还能记得这个成语的意思并准确地使用到恰当的语境中呢？估计会有一定的难度。相反，如果把生成“买椟还珠”这个成语的故事讲给他们听，他们即便不去背，估计也会一辈子都记得的。记忆英语单词也是一样。只是背诵单词及其释义的话，那么尽管当时可能记住了，但很快就又会忘了。从现在起，让我们来听听英语单词背后的造词故事吧，即便不用刻意去记，您也能轻松地记住它们。

### 3. 通过“单词树”串记单词！

想要单词保持长久的记忆效果、需要时能像母语使用者那样自由运用的话，用右脑记忆会取得更好的效果。怎样做才能取得这样的效果呢？您可以尝试着将每天要学的单词用一个主题串联起来，根据其造词原理来构建“单词树”。这样您背的就不是一个孤立抽象的单词，而是通过“单词树”视觉化的具有相互关联性的词群。如果能将单词与相关图片结合起来，则会取得更长久的记忆效果。

<!-- p.5 -->

## 妙招小集锦

### 像读数学公式一样！
**朴成贤（29岁，中学英语会话专门讲师）**

接头词和词源篇曾提到过组成单词的过程就如同理解一个数学公式一样。我们在计算1+2+3等于6的时候，并不是直接就算出了“6”，而是在心里思考“1+2等于3，3再加上3等于6”。大部分英文书是通过前者的方式仅仅告诉学习者“单词及其意思”，而这本书则是通过后一种方法让读者更轻松地记单词。

这本书并不是采取原有的一步到位列举法，如“ab+normal→ abnormal不正常的”，而是通过中间解释的过程，让学习者更容易理解。即“ab+normal→跟正常不一样的，脱离正常的→abnormal 不正常的”。

---

### 跟背汉字的方式惊人的相似！
**郑荷娜（23岁，大学生）**

跟我上大学时背汉字的方式相似，真是太让我吃惊了！一般情况下70%的汉字只要知道部首的意思就能推测出字的意思。这本书也介绍了词根的原理，即使遇到不认识的单词，也能大体推测出它的意思。

---

### 让学习者轻轻松松学英语
**韩成宪（45岁，大学讲师）**

每章的第一页都列出了要学习的单词的原理，让学生一目了然。然后，通过详细的说明让学生真正理解单词的意思。最后，通过练习题的方式进一步巩固。我认为，其中“voca map”和“温馨小提示”部分是理解单词最好的方式。

---

### 单词健忘症消失了！
**黄敏智（20岁，大学生）**

这本书通过故事的方式详细介绍了单词的构造和原理，使我觉得理解起来容易了许多。教材中，每个单词都会让我们反复练习两三遍，即使只看过一遍课本，也不会忘掉已经学过的单词。学习的时候，我似乎并没有觉得有负担，反倒学得很有劲头，单词也能熟练掌握了。现在我已经跟单词健忘症说拜拜了！

---

### 讲故事也适用于英语单词！
**鲁宝蓝（24岁，大学生）**

一直以来，我总觉得记单词没有什么别的办法，只能“无条件死记硬背”。可是通过学习这本书，我慢慢发现用讲故事的方式学习能在无意间记住单词的意思，并熟练掌握单词的用法。“讲故事”这种方式原来也适用于英语单词啊！真是太令人吃惊了！

<!-- p.6 -->

### 送给那些胡乱背英语单词、心生厌倦的人们！

通过学习这本书，我慢慢感觉到记英语单词并不是靠死记硬背，而是一个“自然输入”的过程。通过单词树推测意思，通过故事理解，最后通过自己做练习自然而然地掌握学过的内容。这简直就是一个完美的教程！而且只需要60天的时间就能掌握这个教程，并且在此过程中不会觉得厌倦。我认为，对于那些胡乱背单词，对学习心生厌倦的人来说，这本书是一本值得看的好书。

—— 金慧苑（25岁，大学生）

---

### 无法完全看完一本单词书？

我曾看过很多英文单词书，但总是半途而废。即使是背诵的科目，如果理解起来很困难的话，也很难背过，更何况是英语单词了。但是这本书打破常规，让学习者逐个理解单词的意思并熟记，真是太棒了！现在我再也不会只看前面不学后面了！

—— 韩雅蓝（24岁，韩文教师）

---

### 跟孩子一起学习！

刚开始孩子学英语的时候，我知识告诉他单词的意思，并让他背过。可是读了这本书之后，我把书里所讲的关于英语单词的故事讲给孩子听，孩子觉得很有意思。瞬间，我似乎觉得找到了能跟孩子一起分享的英语书。期待有一天，我能跟孩子一起读英文原著。

—— 朴美淑（41岁，家庭主妇）

---

### 现在每当想到单词的时候，就能想起它的意义！

以前学习单词最让我觉得头疼的是，不管怎么背，脑子里总是想不起单词的意义来，以至于无法恰当地使用。通过学习这本书，我克服了这个一直困扰着我的难题。我个人认为，要想学好单词，就要了解其中所包含的文化，这本书将与单词相关的文化故事以及与词源相关的故事都汇集在一起，给我带来了很大的帮助。

—— 宋智姬（26岁，公司职员）

---

### 在公务员考试中也适合的书！

我现在一边上班一边准备公务员考试。可是对我来说最大的阻碍就是英语单词。我没有充足的时间，也没有好的方法背单词。就在我走投无路的时候，一个偶然的机会让我看到了这本书。以前看10个单词我也就只能记住一个，可是读这本书，看10个我竟然能记住9个，甚至看到别的单词，我也能推测出其中的意思。本来我是想放弃学单词的，现在我又有了想学习的动力。

—— 金京舜（30岁，公司职员）

<!-- p.7 -->

## 本书结构

### Step 1：用“单词树”来类推词义
为了便于每天的学习，请用单词树整理出由一个词源所生成的单词。试着训练自己举一反三推测词义的能力。

### Step 2：利用“故事”来理解、记忆单词
只是死记硬背单词的话，就算当时记住了，也不会记得很久。现在仔细听、仔细看本书所讲的单词生成故事，即便不用刻意去记，您也会牢牢记住的。

### Step 3：通过练习确认记忆效果！
通过各种练习强化对单词的理解与使用，实现良好的记忆效果。

### Step 4：通过 weekly quiz 来巩固！
学过的单词要不断巩固才行！每隔5天做些练习来检查、巩固前面学过的单词。特别标出出错的单词，10天后再对出过错的单词进行确认练习。

### Step 5：随身带着单词本背诵
人的记忆不是输入一次后就能永久保存的。因此，反复地复习是必要的。附录部分整理出了“每日单词记忆表”，您可以按着提示剪成小卡片随身携带学习。

---

> **词性说明**
> 
> *n.*: 名词　*adj.*: 形容词　*adv.*: 副词　*vt.*: 及物动词　*vi.*: 不及物动词
> 
> 【形后】：形容词后缀　【名后】：名词后缀　【动后】：动词后缀

<!-- p.8 -->

### 本书会对哪些人有用？

#### 有背英语单词恐惧症的初学者

如果在对话过程中，有人夹杂了大量外来词或英语，为了让自己不露出听不懂的神色，是不是得小心地控制自己的表情？挺痛苦的吧？恭喜！您已经成为“面部表情管理的达人”了。不过，现在您大可不必再做那种痛苦的事情了。《英语单词超强记忆法》会祝您一臂之力，让您扬眉吐气。如果您是初学者，可以考虑摒弃传统的单词记忆法，将该书中的标题单词单独整理在本子上随身携带，结合着书中的故事来记忆，坚持一段时间后，您会得到意想不到的收获。

<!-- 插图：一人用英语问“Excuse me?”，另一人不知所措 -->

#### 准备中考、高考、托业、托福、GRE、研究生入学考试的考生

从实际讲课来看，英语学习中最让学生感到困难的部分就是“背单词”。为了备战各种英语考试，花在背单词上的时间和精力真的超乎想象。但是，投入的时间与记忆效果并未成正比，背了100个词，差不多会有30%没能记下来。而笔者用本书所阐述的“理解单词记忆法”教了考生10余年，大量的反馈证明该方法是投入时间少、记忆效果好的高效记忆法。那些背了又背却还是忘记、用起来总是混淆的英语单词，现在有了新的攻克方法：通过故事来理解单词，通过词源类推单词，这将是最经济、最有效的单词记忆法。

<!-- 插图：学生在桌前背单词感到苦恼，旁边人问“没关系吗？” -->

#### 应该学英语却没有学习时间的职场人

职场人很难抽出时间专门学习英语，但也不能因此而置英语于不顾。笔者建议忙碌的职场人们充分利用零散时间，每天学本书中的10个主题词。仔细阅读书中每个单词的说明大概需要10分钟时间。如果没有复习的时间，就把当天学的单词写下来贴在显示器上。有空就看一下，看的同时回想一下书中所讲的故事。有空与他人聊天的时候，给对方讲自己所看过的英语单词故事加深印象。要知道，把自己学过的内容讲给别人可是最好的记忆方法哦。

<!-- 插图：拿着文件的职场人士在交流 -->

#### 想成为孩子最棒的英语老师

知道单词准确的词义及用法并将其讲解给孩子听是有难度的事儿。市面上也很难找到一本教授英语单词学习法的书。所以，只能日复一日地重复着机械背单词的行为。现在您不用愁了！有了《英语单词超强记忆法》一书，您可以像讲故事一样每天给孩子讲几个英文单词，通过这种寓教于乐的故事记忆法，您会发现即使遇到复杂难记的单词，孩子也不会有抗拒感了。成为孩子最好的英语老师，您准备好了吗？

<!-- 插图：家长在做饭时与孩子互动交流 -->

<!-- p.9 -->

## 学习日程表

如果每次学习英语都是三分钟热度，那怎么能学好英语呢。俗话说得好：有梦想的人才会成功。英语学习也是一样。既然要学习英语，那就先定个目标和计划，然后坚定不移地实践计划。在实践过程中，您会发现经常会有意想不到的收获。将这些收获积累起来，您的英语水平在不知不觉中就提高了许多。

| | Day 1 | Day 2 | Day 3 | Day 4 | Day 5 | |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| **目标日** | | | | | | **Weekly**<br>**Quiz 01** |
| **实践日** | | | | | | |

| | Day 6 | Day 7 | Day 8 | Day 9 | Day 10 | |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| **目标日** | | | | | | **Weekly**<br>**Quiz 02** |
| **实践日** | | | | | | |

| | Day 11 | Day 12 | Day 13 | Day 14 | Day 15 | |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| **目标日** | | | | | | **Weekly**<br>**Quiz 03** |
| **实践日** | | | | | | |

| | Day 16 | Day 17 | Day 18 | Day 19 | Day 20 | |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| **目标日** | | | | | | **Weekly**<br>**Quiz 04** |
| **实践日** | | | | | | |

| | Day 21 | Day 22 | Day 23 | Day 24 | Day 25 | |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| **目标日** | | | | | | **Weekly**<br>**Quiz 05** |
| **实践日** | | | | | | |

| | Day 26 | Day 27 | Day 28 | Day 29 | Day 30 | |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| **目标日** | | | | | | **Weekly**<br>**Quiz 06** |
| **实践日** | | | | | | |

<!-- p.10 -->

| | Day 31 | Day 32 | Day 33 | Day 34 | Day 35 | Weekly Quiz 07 |
| :--- | :---: | :---: | :---: | :---: | :---: | :---: |
| **目标日** | | | | | | |
| **实践日** | | | | | | |

| | Day 36 | Day 37 | Day 38 | Day 39 | Day 40 | Weekly Quiz 08 |
| :--- | :---: | :---: | :---: | :---: | :---: | :---: |
| **目标日** | | | | | | |
| **实践日** | | | | | | |

| | Day 41 | Day 42 | Day 43 | Day 44 | Day 45 | Weekly Quiz 09 |
| :--- | :---: | :---: | :---: | :---: | :---: | :---: |
| **目标日** | | | | | | |
| **实践日** | | | | | | |

| | Day 46 | Day 47 | Day 48 | Day 49 | Day 50 | Weekly Quiz 10 |
| :--- | :---: | :---: | :---: | :---: | :---: | :---: |
| **目标日** | | | | | | |
| **实践日** | | | | | | |

| | Day 51 | Day 52 | Day 53 | Day 54 | Day 55 | Weekly Quiz 11 |
| :--- | :---: | :---: | :---: | :---: | :---: | :---: |
| **目标日** | | | | | | |
| **实践日** | | | | | | |

| | Day 56 | Day 57 | Day 58 | Day 59 | Day 60 | Weekly Quiz 12 |
| :--- | :---: | :---: | :---: | :---: | :---: | :---: |
| **目标日** | | | | | | |
| **实践日** | | | | | | |

<!-- p.1 -->

## 目录

- **Day 1** 源于Ceres谷物女神的cereal谷物 …… 3
- **Day 2** 被Luna月亮女神所诱惑、半夜里出来乱晃，lunatic疯了 …… 11
- **Day 3** 不容易剥皮、酸了吧唧的lemon是次品 …… 19
- **Day 4** 像slug鼻涕虫一样慢的话就是sluggish！ …… 27
- **Day 5** 像film胶片一样薄，所以是flimsy！ …… 35
- **Day 1-5** Weekly Quiz 1 …… 43
- **Day 6** 扣动trigger扳机子弹就发射了，trigger引发其他事件 …… 44
- **Day 7** 如果壁炉里的火被熄灭cover fire，那就是curfew宵禁 …… 52

- **Day 8** 手是manu，脚是ped …… 63
- **Day 9** 推是pel，拉是tract …… 71
- **Day 10** 走了是ced，来了是ven …… 79
- **Day 6~10** Weekly Quiz 2 …… 87
- **Day 11** 站着是sist，坐着是sid …… 88
- **Day 12** 折起来是plic，展开是tend …… 96
- **Day 13** 清空是van，填满是ple …… 105
- **Day 14** 旋转、改变、变化是vert …… 113
- **Day 15** 放置是pos(e) …… 121
- **Day 11~15** Weekly Quiz 3 …… 129

<!-- p.2 -->

- Day 16　移动、搬运是 fer 和 port …… 133
- Day 17　说是 dic(t)、fa、loq …… 142
- Day 18　看是 spec(t) 和 vid …… 150
- Day 19　呼吸是 spir、心是 anim …… 158
- Day 20　破碎是 frag、爆炸是 rupt …… 166
- Day 16~20　Weekly Quiz 4 …… 174
- Day 21　倾倒是 fus、流是 flu …… 175
- Day 22　触摸是 tag、感受是 sent …… 183
- Day 23　呼喊是 claim、发布是 nounce …… 191
- Day 24　扔是 ject、送是 mit …… 199
- Day 25　抓是 cap、抓着是 tain …… 207
- Day 21~25　Weekly Quiz 5 …… 215
- Day 26　结束是 fin 和 termin …… 216
- Day 27　知道是 gno、not、sci …… 224

- Day 28　去 market、要讲 price …… 235
- Day 29　喝是 drink、掉是 drop …… 243
- Day 30　风是 wind、摇晃是 swing …… 251
- Day 26~30　Weekly Quiz 6 …… 259
- Day 31　众所周知的是 food、最重要的是 health …… 260
- Day 32　低洼凹陷的洞穴 cave、黑暗中发光的蜡烛 candle …… 268
- Day 33　抢夺是 rob、膨胀的是 ball …… 276
- Day 34　招待的人是 host、不能独自生存的是 human …… 284
- Day 35　生命所必需的是 vitamin、多种物质混合掺杂在一起的是 blend …… 292
- Day 31~35　Weekly Quiz 7 …… 300
- Day 36　刮风是 blow、小鸟扑腾是 flap …… 301
- Day 37　首要 prime、首都 capital …… 309
- Day 38　种田产出的 culture、源于 city 的 civilization …… 317
- Day 39　建立是 found、树根、问题的根源是 root …… 326

<!-- p.3 -->

- Day 40 一味否定的 un- ······································· 337
- Day 36~40 Weekly Quiz 8 ······································· 345
- Day 41 否定的 in- ······································· 346
- Day 42 表示向里的 in- ······································· 355
- Day 43 表示出来的 ex- ······································· 364
- Day 44 表示向下坠落脱离的 de- ······································· 373
- Day 45 从这边向那边移动的 trans- ······································· 382
- Day 41~45 Weekly Quiz 9 ······································· 391
- Day 46 一起强调的 com- ······································· 392
- Day 47 分开变没了的 dis- ······································· 400
- Day 48 表示先做的 pre- ······································· 409
- Day 49 表示向前的 pro- ······································· 418
- Day 50 仅次于……的 sub- ······································· 426
- Day 46~50 Weekly Quiz 10 ······································· 434
- Day 51 分离并脱离出来的 ab- ······································· 435
- Day 52 靠近、接近的 ad- ······································· 443
- Day 53 向后绕的 re- ······································· 451
- Day 54 绕了一圈后又重新的 re- ······································· 459

- Day 55 既是木板又是委员会的 board ······································· 469
- Day 51~55 Weekly Quiz 11 ······································· 478
- Day 56 不管是负担、行李，还是费用，只要填满了，就是 charge ······································· 479
- Day 57 不管男女，抑或事情，被缠住了就是 engage ······································· 489
- Day 58 不管账单还是法案，盖了印章的纸都是 bill ······································· 497
- Day 59 不管是造船、还是打马虎眼，凭手艺做事就是 craft ······································· 505
- Day 60 算钱、脑海中的计算都是 account ······································· 514
- Day 56~60 Weekly Quiz 12 ······································· 523

参考答案 ······································· 525

