# Weekly Quiz 4（Day 16~20） {.unnumbered}

> 出自《英语单词超强记忆法》（〔韩〕金炯卓）　原书扫描页 p189–p189

<!-- p.174 -->

语言是需要反复练习的。请在5分钟内写出这5天所学过的下列单词的词义，词义写错的单词在空格内打钩。10天后重新检查出错的单词。

1. job offer ______ [ ]
2. prefer milk coffee to black ______ [ ]
3. differ from ______ [ ]
4. suffer from ______ [ ]
5. confer a medal on the winner ______ [ ]
6. export semiconductors ______ [ ]
7. public transport ______ [ ]
8. financial support ______ [ ]
9. portable radio ______ [ ]
10. deport illegal immigrants ______ [ ]
11. drug addict ______ [ ]
12. economic predicament ______ [ ]
13. dictator ______ [ ]
14. contradictory ______ [ ]
15. indicator ______ [ ]
16. a fabulous meal ______ [ ]
17. affable voice ______ [ ]
18. loquacious ______ [ ]
19. public apology ______ [ ]
20. an eloquent speaker ______ [ ]
21. the positive aspect ______ [ ]
22. circumspect ______ [ ]
23. despicable ______ [ ]
24. expectant mom ______ [ ]
25. life expectancy ______ [ ]
26. conclusive evidence ______ [ ]
27. inspect the incident ______ [ ]
28. improvise a toy ______ [ ]
29. a revised edition ______ [ ]
30. supervise the staff ______ [ ]
31. his aspiration for success ______ [ ]
32. artistic inspiration ______ [ ]
33. conspiracy ______ [ ]
34. expiration ______ [ ]
35. respiration equipment ______ [ ]
36. animate beings ______ [ ]
37. unanimous ______ [ ]
38. animosity ______ [ ]
39. magnanimous ______ [ ]
40. equanimity ______ [ ]
41. fragile glass ______ [ ]
42. frail health ______ [ ]
43. a fragmented society ______ [ ]
44. infringe on his right ______ [ ]
45. a fractious child ______ [ ]
46. go bankrupt ______ [ ]
47. corrupt officials ______ [ ]
48. disrupt the telephone service ______ [ ]
49. a volcanic eruption ______ [ ]
50. the rupture of a blood vessel ______ [ ]

