# Weekly Quiz 10（Day 46~50） {.unnumbered}

> 出自《英语单词超强记忆法》（〔韩〕金炯卓）　原书扫描页 p449–p449

<!-- p.434 -->

> 语言是需要反复练习的。请在5分钟内写出这5天所学过的下列单词的词义，词义写错的单词在空格内打钩，10天后重新检查出错的单词。

| 序号 | 单词/短语 | 词义 | 检查 | 序号 | 单词/短语 | 词义 | 检查 |
|---|---|---|:---:|---|---|---|:---:|
| 1. | collaborative | ______ | $\square$ | 26. | the precarious situation | ______ | $\square$ |
| 2. | compulsion | ______ | $\square$ | 27. | unprecedented | ______ | $\square$ |
| 3. | competence | ______ | $\square$ | 28. | premature death | ______ | $\square$ |
| 4. | confusing | ______ | $\square$ | 29. | a preposterous excuse | ______ | $\square$ |
| 5. | contemplate | ______ | $\square$ | 30. | gain prestige | ______ | $\square$ |
| 6. | create a commotion | ______ | $\square$ | 31. | promote economy growth | ______ | $\square$ |
| 7. | compensation | ______ | $\square$ | 32. | a promising youth | ______ | $\square$ |
| 8. | comprehensive | ______ | $\square$ | 33. | a time of economic prosperity | ______ | $\square$ |
| 9. | conspicuous changes | ______ | $\square$ | 34. | on purpose | ______ | $\square$ |
| 10. | a consummate actor | ______ | $\square$ | 35. | pursue one's own interests | ______ | $\square$ |
| 11. | natural disaster | ______ | $\square$ | 36. | proficient | ______ | $\square$ |
| 12. | disclose the identity of the criminal | ______ | $\square$ | 37. | profuse apology | ______ | $\square$ |
| 13. | dissolute | ______ | $\square$ | 38. | a prominent building | ______ | $\square$ |
| 14. | dissuade | ______ | $\square$ | 39. | prophet | ______ | $\square$ |
| 15. | Don't disturb me. | ______ | $\square$ | 40. | the purport of the speech | ______ | $\square$ |
| 16. | diminish | ______ | $\square$ | 41. | subdue the rebels | ______ | $\square$ |
| 17. | discreet | ______ | $\square$ | 42. | submerge oneself in work | ______ | $\square$ |
| 18. | to one's dismay | ______ | $\square$ | 43. | subtle difference | ______ | $\square$ |
| 19. | disperse the crowd | ______ | $\square$ | 44. | suburb | ______ | $\square$ |
| 20. | dissect a frog | ______ | $\square$ | 45. | succumb to temptation | ______ | $\square$ |
| 21. | precaution of fire | ______ | $\square$ | 46. | suspense | ______ | $\square$ |
| 22. | racial prejudice | ______ | $\square$ | 47. | susceptibility | ______ | $\square$ |
| 23. | preliminary exercise | ______ | $\square$ | 48. | supplant the old system | ______ | $\square$ |
| 24. | presumptuous | ______ | $\square$ | 49. | her supple body | ______ | $\square$ |
| 25. | prior to | ______ | $\square$ | 50. | surreptitious | ______ | $\square$ |

