# Weekly Quiz 2（Day 6~10） {.unnumbered}

> 出自《英语单词超强记忆法》（〔韩〕金炯卓）　原书扫描页 p102–p102

<!-- p.87 -->

语言是需要反复练习的。请在5分钟内写出这5天所学过的下列单词的词义。在词义写错的单词后的方格内打钩，10天后重新检查出错的单词。

| 序号 | 英文 | 词义 | 错题标记 | 序号 | 英文 | 词义 | 错题标记 |
| :--- | :--- | :--- | :---: | :--- | :--- | :--- | :---: |
| 1. | trigger off a riot | ______ | $\square$ | 26. | pedestrian | ______ | $\square$ |
| 2. | caliber | ______ | $\square$ | 27. | impede | ______ | $\square$ |
| 3. | strike a bargain | ______ | $\square$ | 28. | impeach the President | ______ | $\square$ |
| 4. | beckon a waiter | ______ | $\square$ | 29. | expedite deliveries | ______ | $\square$ |
| 5. | blood vessel | ______ | $\square$ | 30. | dispatch the goods | ______ | $\square$ |
| 6. | brace oneself for | ______ | $\square$ | 31. | propel the growth | ______ | $\square$ |
| 7. | brazen | ______ | $\square$ | 32. | compulsory | ______ | $\square$ |
| 8. | burglar | ______ | $\square$ | 33. | impulse buying | ______ | $\square$ |
| 9. | mugger | ______ | $\square$ | 34. | expel the opponent | ______ | $\square$ |
| 10. | colossal | ______ | $\square$ | 35. | repulsive smell | ______ | $\square$ |
| 11. | curfew | ______ | $\square$ | 36. | attractive | ______ | $\square$ |
| 12. | auspicious | ______ | $\square$ | 37. | distract | ______ | $\square$ |
| 13. | accolade | ______ | $\square$ | 38. | extract | ______ | $\square$ |
| 14. | decimate | ______ | $\square$ | 39. | draw up a contract | ______ | $\square$ |
| 15. | grotesque | ______ | $\square$ | 40. | retract one's remarks | ______ | $\square$ |
| 16. | hallmark | ______ | $\square$ | 41. | safety procedure | ______ | $\square$ |
| 17. | boycott | ______ | $\square$ | 42. | follow the legal precedent | ______ | $\square$ |
| 18. | sabotage | ______ | $\square$ | 43. | recession | ______ | $\square$ |
| 19. | economic sanctions | ______ | $\square$ | 44. | accede to his policy | ______ | $\square$ |
| 20. | ostracize | ______ | $\square$ | 45. | excessive | ______ | $\square$ |
| 21. | manual labor | ______ | $\square$ | 46. | book a conference venue | ______ | $\square$ |
| 22. | manufacture a false story | ______ | $\square$ | 47. | conventional | ______ | $\square$ |
| 23. | manipulate public opinion | ______ | $\square$ | 48. | tax revenue | ______ | $\square$ |
| 24. | the manuscript of the novel | ______ | $\square$ | 49. | a souvenir shop | ______ | $\square$ |
| 25. | manifesto | ______ | $\square$ | 50. | intervene in the crisis | ______ | $\square$ |

