# Weekly Quiz 9（Day 41~45） {.unnumbered}

> 出自《英语单词超强记忆法》（〔韩〕金炯卓）　原书扫描页 p406–p406

<!-- p.391 -->

语言是需要反复练习的。请在5分钟内写出这5天所学过的下列单词的词义。词义写错的单词在空格内打钩，10天后重新检查出错的单词。

1. take immediate action ______ □
2. an impolite question ______ □
3. indifferent to cooking ______ □
4. fabulous ______ □
5. innumerable stars ______ □
6. a computer illiterate ______ □
7. an immense palace ______ □
8. impartial judgment ______ □
9. an inevitable decision ______ □
10. be declared insolvent ______ □
11. imprison the thief ______ □
12. insight into the economy ______ □
13. install a new program ______ □
14. invade her privacy ______ □
15. get involved in the scandal ______ □
16. immigrant ______ □
17. natural ingredients ______ □
18. ingenious ______ □
19. ingenuous ______ □
20. the inundated area ______ □
21. emergency room ______ □
22. tangible evidence ______ □
23. exaggerate ______ □
24. exhausted ______ □
25. exhibition ______ □
26. her elaborate present ______ □
27. enormous ______ □
28. eradicate terrorism ______ □
29. extinct animals ______ □
30. exploit natural gas ______ □
31. declare a strike ______ □
32. decline to answer the question ______ □
33. deficient in common sense ______ □
34. deprive him of his money ______ □
35. detached attitude ______ □
36. decadence ______ □
37. deplete natural resources ______ □
38. depreciate share prices ______ □
39. beyond description ______ □
40. deter a thief from invading ______ □
41. break with tradition ______ □
42. transfer money to his account ______ □
43. transform ______ □
44. transparent ______ □
45. transplant ______ □
46. a tranquil village ______ □
47. financial transaction ______ □
48. transgress ______ □
49. transitory ______ □
50. trespass on private land ______ □

