# Weekly Quiz 7（Day 31~35） {.unnumbered}

> 出自《英语单词超强记忆法》（〔韩〕金炯卓）　原书扫描页 p315–p315

<!-- p.300 -->

语言是需要反复练习的。请在5分钟内写出这5天所学过的下列单词的词义。词义写错的单词在空格内打钩，10天后重新检查出错的单词。

1. organic food ______ [ ]
2. be fed up with ______ [ ]
3. fodder for parody ______ [ ]
4. foster ______ [ ]
5. forage for food ______ [ ]
6. healthful ______ [ ]
7. heal the wound ______ [ ]
8. holy ______ [ ]
9. hail a taxi ______ [ ]
10. wholesome food ______ [ ]
11. excavate ______ [ ]
12. cavern ______ [ ]
13. have one's cavity filled in ______ [ ]
14. cage the savage animal ______ [ ]
15. concave lens ______ [ ]
16. candle in the wind ______ [ ]
17. candid ______ [ ]
18. a presidential candidate ______ [ ]
19. incendiary remarks ______ [ ]
20. kindle a candle ______ [ ]
21. robbery ______ [ ]
22. rapist ______ [ ]
23. ravage ______ [ ]
24. rapture ______ [ ]
25. listen with rapt attention ______ [ ]
26. on the ball ______ [ ]
27. cast one's ballot ______ [ ]
28. beer belly ______ [ ]
29. in full bloom[blossom] ______ [ ]
30. bolster ______ [ ]
31. hold a talk show ______ [ ]
32. a hospitable climate ______ [ ]
33. the hospitality industry ______ [ ]
34. hostage ______ [ ]
35. hospice ______ [ ]
36. human race ______ [ ]
37. humble attitude ______ [ ]
38. humiliate him in public ______ [ ]
39. pay homage to ______ [ ]
40. justifiable homicide ______ [ ]
41. lack of vitamin C ______ [ ]
42. a viable plan ______ [ ]
43. vivid memory ______ [ ]
44. vivacious ______ [ ]
45. survival rate ______ [ ]
46. blend in with ______ [ ]
47. a bland story ______ [ ]
48. a blind date ______ [ ]
49. blunder ______ [ ]
50. blonde ______ [ ]

