# Weekly Quiz 11（Day 51~55） {.unnumbered}

> 出自《英语单词超强记忆法》（〔韩〕金炯卓）　原书扫描页 p493–p493

<!-- p.478 -->

语言是需要反复练习的。请在5分钟内写出这5天所学过的下列单词的词义。词义写错的单词在空格内打钩，10天后重新检查出错的单词。

| 序号 | 题目 | 错误标记 | 序号 | 题目 | 错误标记 |
| :--- | :--- | :---: | :--- | :--- | :---: |
| 1. | abnormal behavior ______ | [ ] | 26. | a reciprocal visit ______ | [ ] |
| 2. | absolute power ______ | [ ] | 27. | refrain from smoking ______ | [ ] |
| 3. | be absorbed in the movie ______ | [ ] | 28. | relinquish ______ | [ ] |
| 4. | child abuse ______ | [ ] | 29. | remorse ______ | [ ] |
| 5. | an abundant labor force ______ | [ ] | 30. | reproach ______ | [ ] |
| 6. | abolish the old law ______ | [ ] | 31. | political reform ______ | [ ] |
| 7. | abhor sexism ______ | [ ] | 32. | tax refund ______ | [ ] |
| 8. | have an abortion ______ | [ ] | 33. | reinforce ______ | [ ] |
| 9. | abstain from smoking ______ | [ ] | 34. | reminder ______ | [ ] |
| 10. | an absurd idea ______ | [ ] | 35. | resolute ______ | [ ] |
| 11. | I'll accompany you. ______ | [ ] | 36. | redress injustices ______ | [ ] |
| 12. | accuse him of murder ______ | [ ] | 37. | redundant population ______ | [ ] |
| 13. | affordable price ______ | [ ] | 38. | reiterate one's refusal ______ | [ ] |
| 14. | make allowances for ______ | [ ] | 39. | renown ______ | [ ] |
| 15. | assert one's rights ______ | [ ] | 40. | retrieve a deleted file ______ | [ ] |
| 16. | accumulate a fortune ______ | [ ] | 41. | boarding ______ | [ ] |
| 17. | be acquitted of all the charges ______ | [ ] | 42. | boarding house ______ | [ ] |
| 18. | an adroit politician ______ | [ ] | 43. | across the board ______ | [ ] |
| 19. | be acclaimed as a masterpiece ______ | [ ] | 44. | provides board and lodging ______ | [ ] |
| 20. | apprehend the criminal ______ | [ ] | 45. | have a good command of English ______ | [ ] |
| 21. | urban refuse ______ | [ ] | 46. | command a fine view ______ | [ ] |
| 22. | newly released movie ______ | [ ] | 47. | the authority to dismiss employees ______ | [ ] |
| 23. | reluctant ______ | [ ] | 48. | report the theft to the authorities ______ | [ ] |
| 24. | resigned ______ | [ ] | 49. | authoritative ______ | [ ] |
| 25. | reveal a secret ______ | [ ] | 50. | be fully booked ______ | [ ] |

