# Weekly Quiz 6（Day 26~30） {.unnumbered}

> 出自《英语单词超强记忆法》（〔韩〕金炯卓）　原书扫描页 p274–p274

<!-- p.259 -->

语言是需要反复练习的。请在5分钟内写出这5天所学过的下列单词的词义。词义写错的单词在空格内打钩，10天后重新检查出错的单词。

1. finite ______
2. infinite ______
3. confine the sale ______
4. definite ______
5. refine petroleum ______
6. terminate a discussion ______
7. the interminable movie ______
8. make a long term contract ______
9. a determining factor ______
10. exterminate mosquitoes ______
11. recognize his achievement ______
12. cognizant of the risk ______
13. diagnose the patient ______
14. prognosis ______
15. notice the smoke ______
16. notify him of the result ______
17. be noted for ______
18. notorious ______
19. conscious of the fact ______
20. conscience ______
21. property market ______
22. marketable ______
23. merchant ______
24. TV commercial ______
25. mercenary ______
26. reasonable price ______
27. priceless antiques ______
28. appraise the damage ______
29. the appreciation of raw materials ______
30. depreciate in value ______
31. drink like a fish ______
32. drunk driving ______
33. be drenched with sweat ______
34. drowned in debt ______
35. beverage ______
36. a drop of sweat ______
37. drip through the ceiling ______
38. droop one's head ______
39. dribble the basketbal ______
40. drool over ______
41. window shopping ______
42. gas pedal ______
43. wander the back street ______
44. winnow out ______
45. give vent to ______
46. in full swing ______
47. under one's sway ______
48. sweeping changes ______
49. a swift decision ______
50. swoop in the enemy ______

