# Weekly Quiz 8（Day 36~40） {.unnumbered}

> 出自《英语单词超强记忆法》（〔韩〕金炯卓）　原书扫描页 p360–p360

<!-- p.345 -->

语言是需要反复练习的。请在5分钟内写出这5天所学过的下列单词的词义。词义写错的单词在空格内打钩，10天后重新检查出错的单词。

1. blow up a plane ______ [ ]
2. at full blast ______ [ ]
3. a bloated estimate ______ [ ]
4. be a breeze ______ [ ]
5. a blizzard of emails ______ [ ]
6. the flag flapping in the wind ______ [ ]
7. flagging ______ [ ]
8. flip a coin ______ [ ]
9. flippant ______ [ ]
10. flop down onto the bed ______ [ ]
11. prime minister ______ [ ]
12. primary election ______ [ ]
13. a primitive society ______ [ ]
14. a pristine forest ______ [ ]
15. primeval urges ______ [ ]
16. capitalism ______ [ ]
17. decapitate ______ [ ]
18. precipitation ______ [ ]
19. recapitulate the main point ______ [ ]
20. capsize ______ [ ]
21. culture shock ______ [ ]
22. cult ______ [ ]
23. cultivate new skill ______ [ ]
24. agriculture ______ [ ]
25. an ant colony ______ [ ]
26. spend a civilized evening ______ [ ]
27. a civil war ______ [ ]
28. citadel ______ [ ]
29. urban ______ [ ]
30. rural ______ [ ]
31. found a new company ______ [ ]
32. raise funds for the poor ______ [ ]
33. fundamental science ______ [ ]
34. profound ______ [ ]
35. rock bottom price ______ [ ]
36. root for ______ [ ]
37. have one's X-ray taken ______ [ ]
38. racism ______ [ ]
39. radical ______ [ ]
40. vegetarian ______ [ ]
41. the unemployment rate ______ [ ]
42. be unlikely to do ______ [ ]
43. unlock the mysteries ______ [ ]
44. as usual ______ [ ]
45. be unwilling to do ______ [ ]
46. unbiased ______ [ ]
47. unbridled ______ [ ]
48. unquestionable ______ [ ]
49. social unrest ______ [ ]
50. unruly children ______ [ ]

